### PR TITLE
Run all chunks in an Rmarkdown document

### PR DESCRIPTION
**Pull request by yamad**
This PR allows for better interactive editing of Rmarkdown documents. Users can evaluate one or more R chunks at the same time (using ESS), mimicking some of the features available in `ess-noweb`. That is, the separate code chunks can be run interactively as if it they were part of a continuous script file.

It implements workalikes for `ess-eval-chunk` and `ess-eval-buffer-from-beg-to-here` as requested in https://github.com/vspinu/polymode/issues/94. 

There are surely better ways to achieve most of what's here, but this does the job for this limited case. I'd be interested if there is a cleaner way of detecting the right spans to map over. There's also very little that is ESS/R specific here, so I could see making this generic later.

### CODE REVIEW

**Comment by vspinu** [comment]
Thank you for this and sorry for taking so long. I wonder if eval functionality could be made more generic and not just specific to ess. Have you thought about the good keys for those commands?

**Comment by yamad** [comment]
Yes, it would be nice to make it more generic. But I am not sure how far general we should go.

For the current approach, all that is required is some sort of `eval-region` or `eval-chunk` variable that holds a evaluation function specific to the mode. In the PR, `ess-Rmd-eval-chunk` calling `ess-eval-region` is the only truly ess-specific thing.

We'd have to decide on some generic eval interface (`polymode-eval-*`) that will be useful to all chunkmodes. ess has an outrageously big collection of commands for sending code to an inferior process. I'm not sure to what extent anyone uses them. Other modes, like say `haskell-interactive-mode` or `geiser`, have a much more limited set of commands. All modes seem to have their own keybindings.

Really, the nicest interface would be to make polymode chunks "invisible" so people can just run the commands they are already used to and it just works as if in a single continuous buffer. But I didn't see a sensible way to make that happen.

For keybindings, the `poly-markdown+r-mode-map` keymap is intended to remap whatever keys are used in ess so that people don't have to relearn the bindings. But I noticed a few days ago that this doesn't quite work currently. The ess keymap seems to override these bindings when the buffer enters a chunk.

**Comment by yamad** [comment]
Just to document here. The keybindings ought to be:

Key | Function
----|----------
C-c C-b | *-eval-buffer
C-c C-r | *-eval-region
C-M-x | *-eval-chunk
C-c \<C-up\> | *-eval-buffer-from-beg-to-here
C-c \<C-down\> | *-eval-buffer-from-here-to-end
C-c C-c | *eval-region-or-function-or-paragraph-and-step

**Comment by vspinu** [comment]
> For the current approach, all that is required is some sort of eval-region or eval-chunk variable that holds a evaluation function specific to the mode.

Yes. generic poly-eval-region or poly-eval-string should be enough (ess pipes all commands to ess-send-string). 

The only complication is of how to handle errors. If one chunk produces errors, do we compile further chunks? Or we just don't care about this and let pile it on the user?

> Really, the nicest interface would be to make polymode chunks "invisible" so people can just run the commands they are already used to and it just works as if in a single continuous buffer. But I didn't see a sensible way to make that happen.

This is interesting idea, but it would apply only in code chunks.

> Just to document here. The keybindings are:

I don't think messing with other modes keybindings is a good idea. The eval commands should be on polymode map in M-n. User's can change those if they want.

**Comment by mwlodarczak** [comment]
I think this would be *hugely* useful. In fact, I came across this PR when looking for a solution to this very problem.

On the question of what to do if a chunk fails, I have just had a look at Rstudio, which implement such functions and which continues despite errors. Jupyter notebook fails and stops execution of any remaining chunks.

Personally, I consider the latter to be a safer alternative. Otherwise things could easily go unnoticed, especially if the current R process is being re-used. In any case, perhaps this could be configurable with a variable like `pm-weave-abort-on-error` or something like that?

**Comment by yamad** [comment]
I still use the code from this PR, in case you need something immediate. I looked a bit at making the implementation generic for any REPL. But without another use case beyond Rmarkdown, I had trouble pinning down a design that works for a mostly unknown general case. For emacs users who just generally want _some_ format that can mix text and code, org-babel already fills that role. _If someone can provide another popular use case for a polymode format that needs eval support, that would be helpful._

Unfortunately, there isn't a unified framework for how REPL interaction works in emacs. Each mode implements its eval interaction on its own. To get generic support for it in poly-mode, we'll have to implement some map between what it means to `eval-string` within each mode. Note all the work on [org-babel](https://orgmode.org/worg/org-contrib/babel/) languages that goes into that. I'm not sure `poly-mode` is the right place to support all that adapter code. I see a need for a separate package that generically manages REPL interaction. I've done a little bit of work on it, but the design is still in flux.

**Comment by yamad** [comment]
@vspinu iirc, you were working on an architectural redesign. if I pick this up again, is master stable enough at this point to target a reworked PR? or should I point elsewhere?

**Comment by mwlodarczak** [comment]
Jason Yamada-Hanff <notifications@github.com> writes:

> I still use the code from this PR, in case you need something
> immediate. I looked a bit at making the implementation generic for any
> REPL.

Yes, I have adapted it to my config (with minor changes). It works fine
with both Rmd and Rnw files - many thanks for this. It is just that I
consider it to be such a useful feature while working with knitr that I
think it should be added upstream.

> But without another use case beyond Rmarkdown, I had trouble pinning
> down a design that works for a mostly unknown general case. For emacs
> users who just generally want _some_ format that can mix text and
> code, org-babel already fills that role. _If someone can provide
> another popular use case for a polymode format that needs eval
> support, that would be helpful._

There is also the combination of R and LaTeX (but as I said, your code
works with that already). I know about Org-Babel but I still prefer to
write my documents directly in LaTeX (or, less commonly, markdown).

> Unfortunately, there isn't a unified framework for how REPL
> interaction works in emacs. Each mode implements its eval interaction
> on its own. To get generic support for it in poly-mode, we'll have to
> implement some map between what it means to `eval-string` within each
> mode. Note all the work on
> [org-babel](https://orgmode.org/worg/org-contrib/babel/) languages
> that goes into that. I'm not sure `poly-mode` is the right place to
> support all that adapter code. I see a need for a separate package
> that generically manages REPL interaction. I've done a little bit of
> work on it, but the design is still in flux.

I would be happy to help if you decide to work further on this. But at
the most basic level, wouldn't an alist mapping chunk modes to their
respective eval functions be good enough to begin with?

**Comment by yamad** [comment]
Agreed it would be nice to have upstream.

> But at the most basic level, wouldn't an alist mapping chunk modes to their respective eval functions be good enough to begin with?

Sure, perhaps I am overthinking. A side point: given the use of EIEIO, I think it would instead be a slot holding a function or function reference on the chunk mode object. If the mode supports eval, then you set that slot.

But... I don't personally use any modes other than ESS/R interaction under polymode, so it would be largely a guess for me whether other modes actually work in practice. My guess, given the way other interaction modes are written, is that the most basic mapping will only _mostly_ work. As such, I'd like at least one use case for something other than R evaluation.

**Comment by vspinu** [comment]
>  if I pick this up again, is master stable enough at this point to target a reworked PR? or should I point elsewhere?

The state of the master is not that relevant here. The difficult part is to make this generic. How do we go about  that and which key do we put the eval map on?

To my mind there are essentially 3 ways to go about the generic part:

  1. Add `polymode-eval-region-function` variable which would contain a function taking a region and evaluating it in whatever way
  2. Defining `polymode-eval-region` cl-generic which would dispatch on the concrete instance of the chunkmode object
  3. Do something similar to weaver/exporter subsystem

The first option is more emacsish and simpler, the second is more inline with the polymode design and might better play in the long run if over generic functionality is added to polymode in the future. 

There might be different evaluation strategies for each backend as well. For instance. You might want to eval in the ESS current process, or you might eval in a stand alone R process inside a compile buffer. In this regard this functionality is somewhat similar to weaving and exporting and maybe a similar approach taken for those should be applied here as well. 

I will have to think a bit more about these issue. Frankly, I am not particularly happy with the current weaver/exporter internals, so maybe there is a way to re-design all these with some simple and generic one-side-fits-all approach.

In any case we can go with somethign simple like option 1 above first. We could switch to another implementation later in a backward compatible way if needed. So if you could adapt your pull to that I would be more than happy to merge.

**Comment by malcook** [comment]
@yamad @mwlodarczak @vspinu  I hope I catch your drift and I'm all in and have a few ideas on this.

Yes!  Go generic.  Option 3 is the way!  

> Do something similar to weaver/exporter subsystem

Taking a quick squiz at the PR:

`ess-Rmd-eval-chunk` is not necessary at all.  Just use the ESS command:  `C-c M-b runs the command ess-eval-buffer-and-go`.  Of course this depend upon the implementation of polymode as using narrow-to-buffer.  But I think there is no looking back on this implementation point, and folks using this might as well understand this model.

Asking polymode to implement all the other implemented eval-xxx commands is asking for trouble.  You MUST subvert the major-mode which you are wrapping.  

ESS?  Yes!

SQL?  Sure!

Shell?  Please!

Julia?  Of course.

And there is no reason this needs to be specific to Rmarkdown.  Same approach  should work for Org-mode and NoWeb and the next literate notebook or template language you get to interoperate with polymode.

As you said, we need to figure out a way to use the weaver/exporter subsystem to this end.   We want to let the user execute whatever eval command  they want to using the keystrokes they already know, but **give the user the option to have it executed with the current buffer temporarily switched to the woven context**,  oh, and importantly, **with the cursor positioned at its corresponding  point in the woven context**.

Write something like: (with-woven-spans ...) which does this.

Then write a meta-command bound to, say, M-n M-w (w for woven), which first prompts for another keystroke, and then executes WHATEVER IT IS BOUND TO but inside `with-woven-spans`.

Leave unifying keybinding up to whatever approach the user chooses!  Don't take this on here!   There are a few approaches that redefine keystrokes for dealing with inferior sub-processes so they are more coordinated/unified, which is a good thing if you want this.  But... it is a separate problem.  You can solve this one without touching that one, and save a few nights sleep.

**Comment by malcook** [comment]
> On the question of what to do if a chunk fails

If you like my approach above, you'll like that its answer to this question is, do whatever ESS does (which is continue, alas, but let's not make this polymode's problem!).

**Comment by vspinu** [comment]
> I think tangle is what we want

I don't think tangle is the right approach in general. Evaluation of a chunk might need parameters from the header of the chunk or even header of the file (like in org-mode); chunks could contain different languages, output of the chunk might go into the file directly or into the process buffer etc. This is also why a simple buffer local `polymode-eval-region-function` might not be enough. Most of the time it's up to the inner modes how to evaluate the chunks, but sometimes it's the host mode (org-mode) which should evaluate the chunks.

**Comment by malcook** [comment]
Hmm... 

My suggestion was based on  what I understood the scope of requirements to be, from reading


 - [the commands implemented in the PR](https://github.com/polymode/polymode/pull/129/files#diff-ffd6b33b2b4060c1d8828c19e827d341L457)
 - the authors statements, being:

> I don't personally use any modes other than ESS/R interaction under polymode

> mimicking some of the features available in `ess-noweb`. That is, the separate code chunks can be run interactively as if it they were part of a continuous script file.

and,

 - Reviewing [ess\-noweb\.el](https://github.com/emacs-ess/ESS/blob/master/lisp/ess-noweb.el)

notably *not* stated is 

> _mimicking the features available in RStudio and org-mode_

I agree that the approach I advocate does not address additional requirements, such as

 > Evaluation of a chunk might need parameters from the header of the chunk or even header of the file (like in org-mode); chunks could contain different languages, output of the chunk might go into the file directly or into the process buffer etc. 

Anyway, I use org-mode with babel and am mostly happy with or gotten used to its native behavior.  _Chaque a son gout._  I was just trying to find a faster/better way to approach the problem as stated as I take on understanding this wonderful beast.


Cheers!

**Comment by vspinu** [comment]
I have implemented this functionality in the simplest and most generic way I could think of. The docs are [here](https://polymode.github.io/polymode.github.io/usage/#evaluation-of-chunks). If anyone has any comments or further feature requests (especially concerning parity with R-studio or ess-noweb) please let me know.

**Pull request closed without merging**
