### PR TITLE
[bug] Remove ^L characters

### PR DESCRIPTION
**Pull request by seokbeomKim**
I've used org-brain package that uses polymode internally. But in some environment, Emacs cannot load some polymode functions. I've checked that loading succeeded after removing ^L characters from all files.

Description
- Loading elisp files failed due to the ^L characters
- Error occurred: 
  Error in package--load-files-for-activation: (invalid-function define-hostmode)
Checking /home/sukbeom/.emacs.d/elpa/polymode-20200606.1106...

### CODE REVIEW

**Comment by vspinu** [comment]
This is a standard paragraph delimiter in emacs. A lot of elisp files are using it and I use it throuout my codding. I a surprised to hear that it doesn't load and I really don't think it's the cause of the errors on your side. Could you dig more details?

**Comment by seokbeomKim** [comment]
I've tested the issue in the environment with Emacs 27.1 on Ubuntu, Arch Linux, and WSL.

The problem is that using ^L characters in the package results in org-brain being failed to load right after the package-installation.

Here's step to generate the issue.

Step 1. Normal behavior
- Remove all ^L characters in polymode package and *.elc files in the directory.
- Restart Emacs
- M-x package-reinstall org-brain package (this action will create org-brain.elc file.)
- do (require 'org-brain), then the package is loaded successfully.

Step 2. Abnormal behavior
- Reinstall polymode (at this time, all ^L characters would be recovered)
- Restart Emacs and load polymode. Then do M-x package-reinstall org-brain (this will generate org-brain.elc file which occurs the error)
- (require 'org-brain) then it would be generate the error:
- Remove the org-brain.elc file in the org-brain package, then the package is loaded successfully.

`
Debugger entered--Lisp error: (void-variable org-brain-poly-hostmode)
  #f(compiled-function () #<bytecode 0xe8384502d551903>)()
  eval-after-load("polymode" #f(compiled-function () #<bytecode 0xe8384502d551903>))
  byte-code("\300\301\302\303#\210\304\301\302\305#\210\300\306\307\303#\210\304\306\307\305#\210\300\310\311\303#\210\304\310\311\305#\210\300\312\313\303#\210\304\312\313\305#\210\314\315..." [defalias
org-brain-visualize-add-grandchild org-brain-show-descendant-level nil make-obsolete "0.5" org-brain-visualize-remove-grandchild org-brain-hide-descendant-level org-brain-visualize-add-grandparent
org-brain-show-ancestor-level org-brain-visualize-remove-grandparent org-brain-hide-ancestor-level eval-after-load "polymode" #f(compiled-function () #<bytecode 0xe8384502d551903>)] 4)
  require(org-brain)
  eval((require 'org-brain) t)
  eval-expression((require 'org-brain) nil nil 127)
  funcall-interactively(eval-expression (require 'org-brain) nil nil 127)
  #<subr call-interactively>(eval-expression t nil)
  apply(#<subr call-interactively> eval-expression (t nil))
  call-interactively@ido-cr+-record-current-command(#<subr call-interactively> eval-expression t nil)
  apply(call-interactively@ido-cr+-record-current-command #<subr call-interactively> (eval-expression t nil))
  #f(advice-wrapper :around #<subr call-interactively> call-interactively@ido-cr+-record-current-command)(eval-expression t nil)
  elmacro-record-command(#f(advice-wrapper :around #<subr call-interactively> call-interactively@ido-cr+-record-current-command) eval-expression nil nil)
  apply(elmacro-record-command #f(advice-wrapper :around #<subr call-interactively> call-interactively@ido-cr+-record-current-command) (eval-expression nil nil))
  call-interactively(eval-expression nil nil)
  command-execute(eval-expression)
`

The compiled bytecode that has been generated right after M-x package-reinstall cannot be loaded when polymode uses ^L characters. I guess there is something wrong with generating compiled bytecodes.

**Comment by vspinu** [comment]
yes, it looks like a deeper issue than ^L. If you just delete the elc files in org-brain and polymode does it work as expected?

**Comment by seokbeomKim** [comment]
Yes. it does work as expected if I delete the elc files.

**Comment by seokbeomKim** [comment]
I will close the issue since it is related to byte code generation rather than ^L characters. Thanks for the replies.

**Pull request closed without merging**
